### ISSUE TITLE
App Folder Permissions

### ISSUE THREAD

**Issue by Crayder** [qnnnnez/scpak#1]
I've already taken the ownership of the WindowsApps directory (I even tried using this .reg file https://github.com/XiaofengdiZhu/SurvivalcraftBlocksdataEditor/issues/1#issuecomment-270288205), but I still get the following message when I try to copy a Contents.pak to the Survivalcraft folder:

>You need permission to perform this action

**Comment by qnnnnez** [comment]
Well, I don't think it's a scpak problem.
Close #1.

**Comment by qnnnnez** [comment]
To modify the app, you'd better make a new appx package with the Content.pak replaced, and then install the new appx package.

**Comment by Crayder** [comment]
>Well, I don't think it's a scpak problem.

Obviously it's not a problem with scpak. But the Issue section on GitHub isn't specifically for issues regarding the repo. In fact, the default GitHub Issue labels are bug, duplicate, enhancement, help wanted, invalid, question, and wontfix.

Any responsible developer would help out an innocent person trying to use their program... :)

>To modify the app, you'd better make a new appx package with the Content.pak replaced, and then install the new appx package.

Hmm... how do I make a new appx package? I'll Google that.

**Comment by qnnnnez** [comment]
If you want to work with appx, you need to install Windows SDK first.
https://blogs.msdn.microsoft.com/wsdevsol/2014/02/12/create-a-windows-store-appx-package-and-sign-it/

**Comment by Crayder** [comment]
It won't let me package SC:

```
C:\Program Files (x86)\Windows Kits\10\bin\x64>makeappx pack /d C:\Users\Crayder1100\Desktop\20961CandyRufusGames.Survivalcraft2_2.0.40.0_neutral__c7jxg4av36ap6 /p SC.appx
Microsoft (R) MakeAppx Tool
Copyright (C) 2013 Microsoft.  All rights reserved.

The path (/p) parameter is: "SC.appx"
The content directory (/d) parameter is: "C:\Users\Crayder1100\Desktop\20961CandyRufusGames.Survivalcraft2_2.0.40.0_neutral__c7jxg4av36ap6"
Enumerating files from directory "C:\Users\Crayder1100\Desktop\20961CandyRufusGames.Survivalcraft2_2.0.40.0_neutral__c7jxg4av36ap6"
MakeAppx : warning: Ignoring footprint file "AppxBlockMap.xml".
MakeAppx : warning: Ignoring footprint file "AppxMetadata\CodeIntegrity.cat".
MakeAppx : warning: Ignoring footprint file "AppxSignature.p7x".
Packing 693 file(s) in "C:\Users\Crayder1100\Desktop\20961CandyRufusGames.Survivalcraft2_2.0.40.0_neutral__c7jxg4av36ap6" (content directory) to "SC.appx" (output file name).
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80070005 - Access is denied.
```

**Comment by qnnnnez** [comment]
It seems that the makeappx program has no access to some files.
To make sure it can access all files, copy the appx directory somewhere else and try again.

**Comment by Crayder** [comment]
I've tried it on my desktop and in the root of my usb drive. I even used the administrator prompt. It's still showing the same errors... :/

**Comment by qnnnnez** [comment]
I have no idea why this happens.

**Comment by Crayder** [comment]
Would it be because it's from the Windows Store? Have you packaged SC successfully?

**Comment by qnnnnez** [comment]
Yes I did succeed with Survivalcraft 1.27.x.

**Comment by qnnnnez** [comment]
In spite of making a APPX package and then installing it, it is also possible to _register_ a APPX directory  with unpacked files and make it an APP in Windows.
This method works fine for me.
See the `Add-AppxPackage` cmdlet for detail.

**Comment by Crayder** [comment]
I already tried the Powershell/`Add-AppxPackage` method already, in fact I tried it before I tried `MakeAppX`. I'll try it again though.

**Comment by Crayder** [comment]
So umm, I tried "Appxmanifest.xml" instead of "AppxManifest.xml", all my problems are solved.

**Comment by qnnnnez** [comment]
That's interesting.
