### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by duangsuse** [qnnnnez/scpak#4]
我给scpak写了一个PKGBUILD。在这里 [\_(:з」∠)\_ ](https://github.com/pigfromchina/scpak-pkgbuild)
当测试它的时候，好像无法正常编译。确定不是pkgbuild的问题。
我的操作环境：
[arc@localhost scpak-pkgbuild]$ uname -a
Linux localhost 3.10.49-g7aa3df3 #1
 SMP PREEMPT Wed Nov 16 02:18:02 CST 2016
 armv7l GNU/Linux
*注：是在手机上编译的。不过上次开pr之前也同手机也试了下，成功。*
记录：
[arc@localhost ~]$ cd scpak-pkgbuild/
[arc@localhost scpak-pkgbuild]$ makepkg
==> Making package: scpak 0.3.1-1 (Sun Jun  4 12:18:11 CST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating scpak git repo...
Fetching origin
==> Validating source files with md5sums...
    scpak ... Skipped
==> Extracting sources...
  -> Creating working copy of scpak git repo...
Reset branch 'makepkg'
==> Removing existing $pkgdir/ directory...
==> Starting build()...
==> finished git clone. downloading submodule...
==> finished updating submodule,running cmake...
-- The CXX compiler identification is GNU 7.1.1
-- Check for working CXX compiler: /sbin/c++
-- Check for working CXX compiler: /sbin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- project source: /home/arc/scpak-pkgbuild/src/scpak
-- project binary: /home/arc/scpak-pkgbuild/src/scpak
-- scpak source files: /home/arc/scpak-pkgbuild/src/scpak/./binaryio.cpp/home/arc/scpak-pkgbuild/src/scpak/./main.cpp/home/arc/scpak-pkgbuild/src/scpak/./native.cpp/home/arc/scpak-pkgbuild/src/scpak/./pack.cpp/home/arc/scpak-pkgbuild/src/scpak/./pakfile.cpp/home/arc/scpak-pkgbuild/src/scpak/./scpak.cpp/home/arc/scpak-pkgbuild/src/scpak/./stb.cpp/home/arc/scpak-pkgbuild/src/scpak/./unpack.cpp/home/arc/scpak-pkgbuild/src/scpak/./wav.cpp/home/arc/scpak-pkgbuild/src/scpak/tinyxml2/tinyxml2.cpp
-- executable output: /home/arc/scpak-pkgbuild/src/scpak/bin-- Configuring done
-- Generating done
-- Build files have been written to: /home/arc/scpak-pkgbuild/src/scpak
==> running make...
Scanning dependencies of target scpak
[  9%] Building CXX object CMakeFiles/scpak.dir/binaryio.cpp.o
[ 18%] Building CXX object CMakeFiles/scpak.dir/main.cpp.o
[ 27%] Building CXX object CMakeFiles/scpak.dir/native.cpp.o[ 36%] Building CXX object CMakeFiles/scpak.dir/pack.cpp.o
[ 45%] Building CXX object CMakeFiles/scpak.dir/pakfile.cpp.o
[ 54%] Building CXX object CMakeFiles/scpak.dir/scpak.cpp.o
[ 63%] Building CXX object CMakeFiles/scpak.dir/stb.cpp.o
[ 72%] Building CXX object CMakeFiles/scpak.dir/unpack.cpp.o[ 81%] Building CXX object CMakeFiles/scpak.dir/wav.cpp.o
[ 90%] Building CXX object CMakeFiles/scpak.dir/tinyxml2/tinyxml2.cpp.o
[100%] Linking CXX executable bin/scpak
```
CMakeFiles/scpak.dir/main.cpp.o: In function `.LANCHOR0':
main.cpp:(.data+0x0): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
CMakeFiles/scpak.dir/pack.cpp.o:(.data+0x0): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
CMakeFiles/scpak.dir/pakfile.cpp.o:(.data+0x0): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
CMakeFiles/scpak.dir/scpak.cpp.o:(.data+0x4): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
CMakeFiles/scpak.dir/unpack.cpp.o:(.data+0x0): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
CMakeFiles/scpak.dir/wav.cpp.o:(.data+0x0): multiple definition of `scpak::version'
CMakeFiles/scpak.dir/binaryio.cpp.o:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/scpak.dir/build.make:329: bin/scpak] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/scpak.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by qnnnnez** [comment]
已修复：
https://github.com/qnnnnez/scpak/commit/7557ef5f47498dbcce777894c9747868217fb1f2
